### Query users
GRAPHQL http://localhost:8080/graphql

query {
    users {
        items {
            id
            name
            email
            address {
                id
                street
                city
                zip
                houseNumber
            }
            vehicles {
                enginePower
                type
                producer
                ... on Car{
                    wheels
                }
            }
        }
    }
}

### Query by ID
GRAPHQL http://localhost:8080/graphql

query {
    user(id : "10"){
        id
        name
        email
    }
}

### Save user
GRAPHQL http://localhost:8080/graphql

mutation {
    saveUser(user: {name: "Jack Kotlin", email: "jk@gmail.com", sex: FEMALE, personId: "XX123"}){
        id
        name
        __typename
    }
}

### Update user
GRAPHQL http://localhost:8080/graphql

mutation {
    saveUser(id: "1", user: {name: "Joe Doe JR", email: "joe@test.com", sex: MALE}){
        id
        name
        __typename
    }
}

### delete user
GRAPHQL http://localhost:8080/graphql

mutation {
    deleteUser(id: "3                     ")
}